"""FAB transaction locators.

These are bank-specific selectors only. Transaction behaviour stays in the
shared TransactionsPage so additional banks can reuse the same methods.
"""


class FabHomeLocators:
    demo_url = "http://10.136.2.149:9004/fab/tranportal.htm"

    purchase_link = "//a[normalize-space()='Purchase']"
    refund_link = "//a[normalize-space()='Refund']"
    void_link = "//a[normalize-space()='Void']"
    authorization_link = "//a[normalize-space()='Authorization']"
    capture_link = "//a[normalize-space()='Capture']"
    inquiry_link = "//a[normalize-space()='Inquiry']"
    recurring_list_cards_link = "//a[normalize-space()='Recurring ListCards']"
    recurring_registration_link = "//a[normalize-space()='Recurring Registration']"
    recurring_payment_link = "//a[normalize-space()='Recurring Payment']"
    finalization_api_link = "//a[normalize-space()='Finalization API']"
    home_link = "//a[normalize-space()='Home Page']"

    tid = "#tid"
    version = "#version"
    adgeid1 = "#adgeid1"
    service11 = "#service11"
    password = "#pwd"
    corid = "#corid"
    inquiry_type = "#inqtype"
    amount = "#serAmnt11"
    quantity = "input[name='serQty11']"
    udf1 = "input[name='UDF1']"
    buy_button = "//input[@type='Submit']"
    udf5 = "//select[@name='udf5']"
    udf5_option = "//select[@name='udf5']/option[normalize-space()='{value}']"
    comment = "//input[@name='comment']"
    udf11 = "//*[@id='UDF11']"
    udf12 = "input[name='UDF12']"
    endpoint = "//select[@name='endpoint']"
    endpoint_option = "//select[@name='endpoint']/option[3]"
    project = "//select[@name='path']"
    project_option_mpay = "//select[@name='path']/option[5]"
    project_option_merchant_portal = "//select[@name='path']/option[2]"
    project_option_recurring = "//select[@name='path']/option[6]"
    language = "//select[@id='langEnAr']"
    language_option = "//select[@id='langEnAr']/option[normalize-space()='{value}']"
    header_version = "//input[@id='headerVersion']"
    refund_id = "//*[@id='text']/input"
    entity_id = "//input[@id='entityId']"

    dynamic_amount1 = "//input[@id='amount11']"
    dynamic_amount2 = "//input[@id='amount12']"
    dynamic_amount3 = "//input[@id='amount13']"
    service2 = "//input[@id='service12']"
    service_amount2 = "//input[@id='serAmnt12']"
    vendor_adgeid1 = "//input[@id='adgeid2']"
    vendor_adgeid2 = "//input[@id='adgeid3']"
    vendor_service1 = "//input[@id='service21']"
    vendor_service1_amount = "//input[@id='serAmnt21']"
    vendor_service2 = "//input[@id='service31']"
    vendor_service2_amount = "//input[@id='serAmnt31']"
    vendor_dynamic_amount1 = "//input[@id='amount21']"
    vendor_dynamic_amount2 = "//input[@id='amount22']"
    vendor_dynamic_amount3 = "//input[@id='amount23']"

    back_to_merchant = "/html/body/div/div/div[5]/button[1]"
    download_receipt = "/html/body/div/div/div[5]/button[2]"
    body = "body"
    final_api_body = "/html/body/table[2]/tbody/tr[1]/td/i"
    recurring_id = "//label[contains(text(),'Recurring ID')]"
    recurring_id_input = "//input[@id='recurringId']"
    card_id_value = "/html/body/h4[1]/font[2]"
    card_id_input = "//input[@id='cardId']"
    finalization_api_payment_id = "//input[@id='paymentID']"
    result_message = 'font[color="grey"]'
    refund_assert = "/html/body/h4[1]/font[2]"


class FabAdpayLocators:
    change_payment = "//a[@id='Change']"
    select_payment = "//div[@id='addNewCardOffcanvas']"

    add_heading = ("role", "heading", {"name": "Add"})
    name_textbox = ("role", "textbox", {"name": "Enter name"})
    card_textbox = ("role", "textbox", {"name": "Enter card number"})
    cvv_textbox = ("role", "textbox", {"name": "***"})
    email_textbox = ("role", "textbox", {"name": "Enter Email Address"})
    select_month = "//*[@id='add-creditcard']/div[4]/div[1]/div[1]/div[1]"
    select_month_option = "//*[@id='add-creditcard']/div[4]/div[1]/div[1]/div[2]/div[12]"
    select_year = "//*[@id='add-creditcard']/div[4]/div[2]/div[1]/div[1]"
    select_year_option = "//*[@id='add-creditcard']/div[4]/div[2]/div[1]/div[2]/div[4]"

    payment_pay_button = "//*[@id='ConfirmPay']"
    payment_change_pay_button = "//*[@id='payment']"
    payment_yes_button = "//*[@id='yesclick1']/button"
    confirm_yes_button = "//*[@id='yesclick2']/button"

    comerapay = "//div[@id='comerapayFav']"
    comerapay_registered_number = "//input[@id='comeraMobileNumber']"
    comerapay_request_otp = "//button[@id='comeraWalletSubmit']"
    comerapay_otp = ("role", "textbox", {"name": "Enter OTP"})
    comerapay_confirm_button = "//button[@id='comeraPayAuth']"

    direct_debit = "//div[normalize-space()='Direct Debit']"
    bank_list = "//select[@id='ddl_BanksList']"
    bank_list_option = "//select[@id='ddl_BanksList']/option[normalize-space()='{value}']"
    product_list = "//select[@id='ddl_ProductList']"
    product_list_option = "//select[@id='ddl_ProductList']/option[normalize-space()='{value}']"
    submit_button = "//*[@value='Submit']"
    terms_checkbox = "//*[@id='CheckBoxTerms']"
    response_code = "//input[@name='pp_ResponseCode']"
    response_message = "//input[@id='pp_ResponseMessage']"
    auth_code = "//input[@id='pp_AuthCode']"
    bank_id = "//input[@id='pp_BankID']"
    generate_hash = "//*[@value='Generate Hash']"
    return_to_pg = "//*[@value='Return to PG']"

    dirham_symbol = "#symbolar"
    dirham_symbol_ar = "#symbolen"
    summary_header = "#SummaryEN"
    summary_header_ar = "#SummaryAR"
    payment_response = "td[style='word-break: break-word;']"
    inquiry_response = 'font[color="grey"]'

    charity1_amount5 = "//button[@id='charity5_1']"
    charity1_amount10 = "//button[@id='charity10_1']"
    charity1_other = "//div[@id='other_1']"
    charity1_other_amount = "//input[@id='charityAmountCards_row_1']"
    charity2_amount5 = "//button[@id='charity5_2']"
    charity2_amount10 = "//button[@id='charity10_2']"
    charity2_other = "//div[@id='other_2']"
    charity2_other_amount = "//input[@id='charityAmountCards_row_2']"
    charity3_amount5 = "//button[@id='charity5_3']"
    charity3_amount10 = "//button[@id='charity10_3']"
    charity3_other = "//div[@id='other_3']"
    charity3_other_amount = "//input[@id='charityAmountCards_row_3']"

    change_ar = "//a[@id='ChangeAR']"
    add_new_card_ar = "//h5[@id='add-new-card']"
    cardholder_name_ar = "//input[@id='cardholderName']"
    card_number_ar = "//input[@name='cardNumber']"
    card_cvv_ar = "//input[@id='cardCvv']"
    comerapay_ar = "//div[normalize-space()='Comera Wallet']"
    charity1_amount5_ar = "//button[@id='charity5AR_1']"
    charity1_amount10_ar = "//button[@id='charity10AR_1']"
    charity1_other_ar = "//div[@id='otherAR_1']"
    charity2_amount5_ar = "//button[@id='charity5AR_2']"
    charity2_amount10_ar = "//button[@id='charity10AR_2']"
    charity2_other_ar = "//div[@id='otherAR_2']"
    charity3_amount5_ar = "//button[@id='charity5AR_3']"
    charity3_amount10_ar = "//button[@id='charity10AR_3']"
    charity3_other_ar = "//div[@id='otherAR_3']"

    recurring_saved_card = "//input[@id='proceed']"
    cancel_button = "//input[@id='cancel']"
    recurring_month = "//div[@id='ExpDate']/div/div[1]/div/div[1]"
    recurring_month_option = "//div[@id='ExpDate']/div/div[1]/div/div[2]/div[8]"
    recurring_year = "//div[@id='ExpDate']/div/div[2]/div/div[1]"
    recurring_year_option = "//div[@id='ExpDate']/div/div[2]/div/div[2]/div[3]"

    saved_card_mastercard = "//div[@cardkey='202417322764593']"
    saved_card_mastercard_cvv = "//input[@id='savedcardCVV_5204-74**-****-1002']"
    saved_card_amex = "//div[@cardkey='202607686057208']"
    saved_card_amex_cvv = "//input[@id='savedcardCVV_3791-87**-***-4105']"
    saved_card_visa = "//div[@cardkey='202504166662198']"
    saved_card_visa_cvv = "//input[@id='savedcardCVV_4012-00**-****-1112']"
    saved_card_jaywan = "//div[@cardkey='202608488163239']"
    saved_card_jaywan_cvv = "//input[@id='savedcardCVV_6690-09**-****-6376']"
    view_more = "//p[@id='viewmore']"


class FabMpayLocators:
    click_tabby = "//label[@id='PaymentpageTranoptions'][@for='tabby_inst']"
    click_uaepgs = "//label[normalize-space()='Direct Debit']"
    click_pay = "//input[@id='proceed']"
    receipt_email = "//*[@id='email']"
    new_card = "//div[@id='RegNewCard']"
    cardholder_name = "//input[@name='cardholderName']"
    card_number = "//input[@name='cardNumber']"
    cvv = "//input[@id='cardCvv']"
    expiry_month = "//select[@id='ExpMonthSelect']"
    expiry_year = "//select[@id='ExpYearSelect']"
    expiry_month_option = "//select[@id='ExpMonthSelect']/option[normalize-space()='{value}']"
    expiry_year_option = "//select[@id='ExpYearSelect']/option[normalize-space()='{value}']"
    charity1 = "//*[@id='charity_pay']/div[1]/div[1]/div/label/div"
    charity2 = "//*[@id='charity_pay']/div[2]/div[1]/div/label/div"
    charity3 = "//*[@id='charity_pay']/div[3]/div[1]/div/label/div"
    charity1_amount = "//input[@id='charityAmountCards_row_1']"
    saved_card = "//div[@cardkey='202417370959348'][@id='EN_2_5204-74**-****-1002']"
    saved_card_cvv = "//input[@id='EN_savedcardCVV_5204-74**-****-1002']"
    tabby_email = "//input[@name='email']"
    tabby_continue = "//span[normalize-space()='Continue']"
    tabby_otp = "//*[@name='otp-code']"
    tabby_check_box = "//input[@id='checkAll']"
    tabby_installment = "//div[@data-test='payment-plans.installments-item'][4]"
    tabby_installment_continue = "//span[normalize-space()='Continue']"
    direct_debit = "//div[normalize-space()='Direct Debit']"
    bank_list = "//select[@id='ddl_BanksList']"
    product_list = "//select[@id='ddl_ProductList']"
    submit_button = "//*[@value='Submit']"
    terms_checkbox = "//*[@id='CheckBoxTerms']"
    response_code = "//input[@name='pp_ResponseCode']"
    response_message = "//input[@id='pp_ResponseMessage']"
    auth_code = "//input[@id='pp_AuthCode']"
    bank_id = "//input[@id='pp_BankID']"
    generate_hash = "//*[@value='Generate Hash']"
    return_to_pg = "//*[@value='Return to PG']"
    payment_response = "td[style='word-break: break-word;']"
    inquiry_response = 'font[color="grey"]'

    charity1_ar = "//div[@id='charity_pay_AR']/div[1]/div[1]/label/div/div"
    charity1_amount_ar = "//input[@id='charityAmountCards_AR_row_1']"
    charity2_ar = "//div[@id='charity_pay_AR']/div[2]/div[1]/label/div/div"
    charity2_amount_ar = "//input[@id='charityAmountCards_AR_row_2']"
    charity3_ar = "//div[@id='charity_pay_AR']/div[3]/div[1]/label/div/div"
    charity3_amount_ar = "//input[@id='charityAmountCards_AR_row_3']"
    tabby_continue_ar = "//button[@data-test='loginForm.continue']"
    tabby_otp_continue_ar = "//button[@data-test='button']"
    tabby_final_continue_ar = "//button[@data-test='payment-plans.continue']"

    recurring_cardholder_name = "//input[@id='EN_cardholderName']"
    recurring_card_number = "//input[@id='EN_cardNumber']"
    recurring_cvv = "//input[@id='EN_cardCvv']"
    recurring_expiry_month = "//select[@id='EN_ExpMonthSelect']"
    recurring_expiry_year = "//select[@id='EN_ExpYearSelect']"
    recurring_expiry_month_option = "//select[@id='EN_ExpMonthSelect']/option[normalize-space()='{value}']"
    recurring_expiry_year_option = "//select[@id='EN_ExpYearSelect']/option[normalize-space()='{value}']"
    recurring_saved_card = "//input[@id='proceed']"
