[pytest]
addopts = --screenshot=on 
          -v --alluredir=./report/allure-results
          --clean-alluredir 
          -q

log_cli = true
log_cli_level = INFO

testpaths = tests

markers =
    regression_sanity: tests that belong to both regression and sanity suites
    regression: full regression suite tests
    sanity: sanity/quick validation tests
    smoke: smoke tests for critical paths